name: Docker Release

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: |
          pnpm --filter @vibe/shared-types build
          pnpm --filter @vibe/tab-extraction-core build
          pnpm --filter @vibe/mcp-rag build
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/co-browser/vibe-rag-server:latest -t ghcr.io/co-browser/vibe-rag-server:${{ github.ref_name }} -f packages/mcp-rag/Dockerfile.simple .
          docker push ghcr.io/co-browser/vibe-rag-server:latest
          docker push ghcr.io/co-browser/vibe-rag-server:${{ github.ref_name }}
      
      - name: Deploy to Coolify
        env:
          COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
        if: env.COOLIFY_API_TOKEN != ''
        run: |
          curl -X GET \
            -H "Authorization: Bearer $COOLIFY_API_TOKEN" \
            "https://coolify.cobrowser.xyz/api/v1/deploy?uuid=tgg4k08s0ckwkcwg00cwggs4&force=false"