
name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write
  attestations: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # Run CI validation first
  validate:
    name: Validate Build
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  # Create the release
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      released: ${{ steps.semantic-release.outputs.new_release_published }}
      version: ${{ steps.semantic-release.outputs.new_release_version }}
      notes: ${{ steps.semantic-release.outputs.new_release_notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build Python Backend
        run: |
          export release_date=20250610
          export filename=cpython-3.13.4+20250610-aarch64-apple-darwin-install_only_stripped.tar.gz
          standalone_python="python/"
          if [ ! -d "$standalone_python" ]; then
            wget https://github.com/indygreg/python-build-standalone/releases/download/${release_date}/${filename}
            tar -xzvf ${filename}
            rm -rf ${filename}
            ./python/bin/python3.13 -m venv .venv
            source .venv/bin/activate
            python3.13 -m pip --isolated --require-virtualenv --no-input install pyinstaller python-dotenv dotenv
            python3.13 -m pip --isolated --require-virtualenv --no-input install apps/mcp-server/vibe-memory-rag/.
          fi
      - name: Sign and Notarize DMG
        env:
          VIBE_VERSION: ${{ env.RELEASE_VERSION }}
          #the password for cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          #csc_link is    CSC_LINK=$(openssl base64 -in cert.p12 
          CSC_LINK: ${{ secrets.CSC_LINK }}
          #dev email
          APPLE_ID: ${{ secrets.APPLE_ID }}
          #mandatory app password, not reg password
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          #apple dev team id
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          echo "Building version: $VIBE_VERSION"
          pnpm run build:mac
        # add upload artifact
      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Notify Discord on successful release
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.released == 'true'
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🚀 **New Release: v${{ needs.release.outputs.version }}**
            
            Repository: **${{ github.repository }}**
            Release Notes: ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ needs.release.outputs.version }}
            
            ${{ needs.release.outputs.notes }}
